"""Add delivery_rate to sellers

Revision ID: 0471d5c038a9
Revises: 0bad6bc2e6e6
Create Date: 2026-02-04 22:47:17.808185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0471d5c038a9'
down_revision = '0bad6bc2e6e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('delivery_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'delivery_rate')
    # ### end Alembic commands ###
