"""Add latitude and longitude to products

Revision ID: 0bad6bc2e6e6
Revises: 05235e7af39f
Create Date: 2026-02-04 19:27:08.918956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bad6bc2e6e6'
down_revision = '05235e7af39f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'longitude')
    op.drop_column('products', 'latitude')
    # ### end Alembic commands ###
