"""Add delivery_per_km to sellers

Revision ID: 6a7d2c1f9c4b
Revises: 92828a77b45a
Create Date: 2026-02-10 00:54:27.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a7d2c1f9c4b'
down_revision = '92828a77b45a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('delivery_per_km', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'delivery_per_km')
    # ### end Alembic commands ###