"""Add latitude and longitude to sellers

Revision ID: 92828a77b45a
Revises: 0471d5c038a9
Create Date: 2026-02-05 10:48:03.259283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92828a77b45a'
down_revision = '0471d5c038a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('sellers', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'longitude')
    op.drop_column('sellers', 'latitude')
    # ### end Alembic commands ###
