"""Create Cart and CartItem tables

Revision ID: a9907d43b5eb
Revises: c5350922bb29
Create Date: 2026-02-02 21:59:18.169812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9907d43b5eb'
down_revision = 'c5350922bb29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
