"""Add is_blocked to users and approved to sellers

Revision ID: e29b4ec8cf9f
Revises: b9c66b0f4d08
Create Date: 2026-02-03 00:38:24.978079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29b4ec8cf9f'
down_revision = 'b9c66b0f4d08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('approved', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_blocked')
    op.drop_column('sellers', 'approved')
    # ### end Alembic commands ###
